# Generated by Django 5.2 on 2025-05-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.SmallIntegerField()),
                ('protein', models.SmallIntegerField()),
                ('carbohydrates', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('fats', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macros.food')),
            ],
        ),
    ]
