# Generated by Django 5.2 on 2025-05-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='food',
            name='name_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name_id',), name='unique_food_name'),
        ),
        migrations.AddField(
            model_name='log',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='macros.food'),
        ),
    ]
